#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Spec: 004-set-up-your-teams

set -e

echo "========================================"
echo "Set up your teams - Administrative Task"
echo "========================================"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}IMPORTANT:${NC} This is a non-technical administrative task."
echo ""
echo "This task involves configuring teams in Linear's project management"
echo "platform and does NOT require any code changes to the ACGS2 monorepo."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${YELLOW}NO SERVICES NEED TO BE STARTED${NC}"
echo ""
echo "This is an administrative task that operates entirely within"
echo "Linear's platform. No development environment setup is required."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ============================================
# TASK OVERVIEW
# ============================================

echo "Task: Set up your teams (Linear Issue XN-2)"
echo ""
echo "Workflow Type: simple (administrative)"
echo "Total Phases: 3"
echo "Total Subtasks: 5"
echo "Services Involved: None (Linear platform only)"
echo ""

# ============================================
# REQUIRED ACTIONS
# ============================================

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Required Actions:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Phase 1: Documentation Review"
echo "  → Review Linear Workspace documentation"
echo "     https://linear.app/docs/workspaces"
echo ""
echo "  → Review Linear Teams documentation"
echo "     https://linear.app/docs/teams"
echo ""
echo "  → Review Linear Members documentation"
echo "     https://linear.app/docs/invite-members"
echo ""
echo "Phase 2: Workspace Verification"
echo "  → Check current state of Linear workspace"
echo "  → Determine if teams are already configured"
echo ""
echo "Phase 3: Task Completion"
echo "  → Mark Linear issue XN-2 as complete"
echo "  → OR invite team members via:"
echo "     http://linear.app/settings/members"
echo ""

# ============================================
# COMPLETION OPTIONS
# ============================================

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Completion Options:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Option 1: If teams are already configured"
echo "  → Simply mark Linear issue XN-2 as complete"
echo ""
echo "Option 2: If teams need to be set up"
echo "  → Follow Linear documentation to configure teams"
echo "  → Invite members via Linear settings"
echo "  → Mark Linear issue XN-2 as complete"
echo ""
echo "Option 3: If not applicable (solo project)"
echo "  → Close Linear issue XN-2 as 'Won't Do'"
echo ""

# ============================================
# IMPORTANT NOTES
# ============================================

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${RED}IMPORTANT NOTES:${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  • NO CODE CHANGES are required for this task"
echo "  • NO SERVICES need to be started"
echo "  • This task operates entirely within Linear's platform"
echo "  • The implementation agent should NOT write any code"
echo "  • Verification is manual (checking Linear workspace state)"
echo ""

# ============================================
# NEXT STEPS
# ============================================

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}Ready to proceed!${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "To start the implementation (administrative verification):"
echo ""
echo -e "  ${BLUE}source auto-claude/.venv/bin/activate && python auto-claude/run.py --spec 004 --parallel 1${NC}"
echo ""
echo "The implementation agent will:"
echo "  1. Guide you through reviewing Linear documentation"
echo "  2. Help verify your Linear workspace configuration"
echo "  3. Assist with marking the Linear issue as complete"
echo ""
echo "========================================"
