"""
Data models for Compliance Documentation Service

Pydantic models for compliance evidence, reports, and export requests
covering SOC 2, ISO 27001, GDPR, and EU AI Act frameworks.
"""

from .base import (
    ComplianceBaseModel,
    ComplianceFramework,
    ComplianceReportMetadata,
    ControlEvidence,
    EvidenceStatus,
    ExportFormat,
    ExportRequest,
    ReportGenerationRequest,
    ReportGenerationResponse,
    VersionedDocument,
)
from .euaiact import (
    AISystemDescription,
    ConformityAssessment,
    ConformityAssessmentType,
    DataGovernanceRecord,
    EUAIActExportRequest,
    EUAIActReportData,
    EUDeclarationOfConformity,
    HighRiskCategory,
    ProviderInformation,
    ProviderRole,
    QualityManagementSystem,
    RiskAssessmentResult,
    RiskLevel,
    RiskManagementRecord,
    TechnicalDocumentation,
    TransparencyObligation,
)
from .gdpr import (
    ContactDetails,
    ControllerRecord,
    DataCategory,
    DataFlowMapping,
    DataProtectionOfficer,
    DataRecipient,
    DataSubjectCategory,
    EntityRole,
    GDPRExportRequest,
    GDPRReportData,
    LawfulBasis,
    ProcessingActivity,
    ProcessorRecord,
    RetentionPolicy,
    SecurityMeasure,
    TransferMechanism,
)
from .iso27001 import (
    ControlApplicability,
    ControlTheme,
    ControlThemeSection,
    ImplementationStatus,
    ISO27001Control,
    ISO27001ControlEvidence,
    ISO27001ControlMapping,
    ISO27001EvidenceMatrix,
    ISO27001ExportRequest,
    ISO27001ReportData,
    StatementOfApplicability,
    StatementOfApplicabilityEntry,
)
from .soc2 import (
    ControlEffectiveness,
    SOC2Control,
    SOC2ControlEvidence,
    SOC2ControlMapping,
    SOC2EvidenceMatrix,
    SOC2ExportRequest,
    SOC2ReportData,
    SystemDescription,
    TrustServiceCriteria,
    TrustServiceCriteriaSection,
)

__all__ = [
    # Base models
    "ComplianceBaseModel",
    "ComplianceFramework",
    "ComplianceReportMetadata",
    "ControlEvidence",
    "EvidenceStatus",
    "ExportFormat",
    "ExportRequest",
    "ReportGenerationRequest",
    "ReportGenerationResponse",
    "VersionedDocument",
    # SOC 2 models
    "ControlEffectiveness",
    "SOC2Control",
    "SOC2ControlEvidence",
    "SOC2ControlMapping",
    "SOC2EvidenceMatrix",
    "SOC2ExportRequest",
    "SOC2ReportData",
    "SystemDescription",
    "TrustServiceCriteria",
    "TrustServiceCriteriaSection",
    # ISO 27001 models
    "ControlApplicability",
    "ControlTheme",
    "ControlThemeSection",
    "ImplementationStatus",
    "ISO27001Control",
    "ISO27001ControlEvidence",
    "ISO27001ControlMapping",
    "ISO27001EvidenceMatrix",
    "ISO27001ExportRequest",
    "ISO27001ReportData",
    "StatementOfApplicability",
    "StatementOfApplicabilityEntry",
    # GDPR models
    "ContactDetails",
    "ControllerRecord",
    "DataCategory",
    "DataFlowMapping",
    "DataProtectionOfficer",
    "DataRecipient",
    "DataSubjectCategory",
    "EntityRole",
    "GDPRExportRequest",
    "GDPRReportData",
    "LawfulBasis",
    "ProcessingActivity",
    "ProcessorRecord",
    "RetentionPolicy",
    "SecurityMeasure",
    "TransferMechanism",
    # EU AI Act models
    "AISystemDescription",
    "ConformityAssessment",
    "ConformityAssessmentType",
    "DataGovernanceRecord",
    "EUAIActExportRequest",
    "EUAIActReportData",
    "EUDeclarationOfConformity",
    "HighRiskCategory",
    "ProviderInformation",
    "ProviderRole",
    "QualityManagementSystem",
    "RiskAssessmentResult",
    "RiskLevel",
    "RiskManagementRecord",
    "TechnicalDocumentation",
    "TransparencyObligation",
]
