apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: acgs2-mirrormaker2
  namespace: kafka
  labels:
    app: acgs2-mirrormaker2
    acgs2/component: messaging
    acgs2/multi-region: enabled
spec:
  version: 3.6.0
  replicas: 2

  # Connect cluster configuration
  connectCluster: "mirrormaker2-cluster"

  # Mirror configuration
  mirrors:
  # Mirror from US East to EU West
  - sourceCluster: "us-east-1"
    targetCluster: "eu-west-1"
    sourceConnector:
      config:
        replication.factor: 3
        offset-syncs.topic.replication.factor: 3
        sync.group.offsets.enabled: true
        sync.group.offsets.interval.seconds: 10
        refresh.topics.enabled: true
        refresh.topics.interval.seconds: 60
        topics: "acgs2\\.events\\..*,acgs2\\.audit\\..*,acgs2\\.governance\\..*"
        topics.exclude: "acgs2\\.events\\.local\\..*,.*\\.internal\\..*"
        replication.policy.class: "org.apache.kafka.connect.mirror.IdentityReplicationPolicy"
        offset.lag.max: 100
        emit.heartbeats.enabled: true
        emit.heartbeats.interval.seconds: 30
        heartbeats.topic.replication.factor: 3
        checkpoints.topic.replication.factor: 3
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 3
        emit.heartbeats.interval.seconds: 30
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 3
        sync.group.offsets.enabled: true
        sync.group.offsets.interval.seconds: 10
        emit.checkpoints.interval.seconds: 60

  # Mirror from EU West to US East
  - sourceCluster: "eu-west-1"
    targetCluster: "us-east-1"
    sourceConnector:
      config:
        replication.factor: 3
        offset-syncs.topic.replication.factor: 3
        sync.group.offsets.enabled: true
        sync.group.offsets.interval.seconds: 10
        refresh.topics.enabled: true
        refresh.topics.interval.seconds: 60
        topics: "acgs2\\.events\\..*,acgs2\\.audit\\..*,acgs2\\.governance\\..*"
        topics.exclude: "acgs2\\.events\\.local\\..*,.*\\.internal\\..*"
        replication.policy.class: "org.apache.kafka.connect.mirror.IdentityReplicationPolicy"
        offset.lag.max: 100
        emit.heartbeats.enabled: true
        emit.heartbeats.interval.seconds: 30
        heartbeats.topic.replication.factor: 3
        checkpoints.topic.replication.factor: 3
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 3
        emit.heartbeats.interval.seconds: 30
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 3
        sync.group.offsets.enabled: true
        sync.group.offsets.interval.seconds: 10
        emit.checkpoints.interval.seconds: 60

  # Clusters configuration
  clusters:
  - alias: "us-east-1"
    bootstrapServers: kafka-cluster-us-east-1-kafka-bootstrap.kafka.svc.cluster.local:9093
    tls:
      trustedCertificates:
      - secretName: kafka-cluster-us-east-1-cluster-ca-cert
        certificate: ca.crt
    authentication:
      type: tls
      certificateAndKey:
        secretName: kafka-mirrormaker-tls
        certificate: user.crt
        key: user.key
    config:
      config.storage.replication.factor: 3
      offset.storage.replication.factor: 3
      status.storage.replication.factor: 3
      # Consumer configuration
      consumer.isolation.level: read_committed
      consumer.auto.offset.reset: earliest
      consumer.max.poll.records: 500
      consumer.fetch.max.bytes: 52428800
      consumer.max.partition.fetch.bytes: 1048576
      # Producer configuration
      producer.acks: all
      producer.max.in.flight.requests.per.connection: 1
      producer.enable.idempotence: true
      producer.compression.type: lz4
      producer.batch.size: 32768
      producer.linger.ms: 5

  - alias: "eu-west-1"
    bootstrapServers: kafka-cluster-eu-west-1-kafka-bootstrap.kafka.svc.cluster.local:9093
    tls:
      trustedCertificates:
      - secretName: kafka-cluster-eu-west-1-cluster-ca-cert
        certificate: ca.crt
    authentication:
      type: tls
      certificateAndKey:
        secretName: kafka-mirrormaker-tls
        certificate: user.crt
        key: user.key
    config:
      config.storage.replication.factor: 3
      offset.storage.replication.factor: 3
      status.storage.replication.factor: 3
      # Consumer configuration
      consumer.isolation.level: read_committed
      consumer.auto.offset.reset: earliest
      consumer.max.poll.records: 500
      consumer.fetch.max.bytes: 52428800
      consumer.max.partition.fetch.bytes: 1048576
      # Producer configuration
      producer.acks: all
      producer.max.in.flight.requests.per.connection: 1
      producer.enable.idempotence: true
      producer.compression.type: lz4
      producer.batch.size: 32768
      producer.linger.ms: 5

  # External configuration
  externalConfiguration:
    volumes:
    - name: mirrormaker-config
      configMap:
        name: mirrormaker-config
---
# ConfigMap for additional MirrorMaker configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: mirrormaker-config
  namespace: kafka
  labels:
    app: acgs2-mirrormaker2
    acgs2/component: messaging
data:
  # MirrorMaker 2 worker configuration
  worker.properties: |
    # Worker configuration
    bootstrap.servers=us-east-1:9093,eu-west-1:9093
    group.id=acgs2-mirrormaker2
    key.converter=org.apache.kafka.connect.json.JsonConverter
    value.converter=org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable=false
    value.converter.schemas.enable=true
    offset.flush.interval.ms=10000
    offset.flush.timeout.ms=5000

    # Plugin path for MirrorMaker
    plugin.path=/opt/kafka/plugins

    # REST API configuration
    rest.advertised.host.name=acgs2-mirrormaker2
    rest.advertised.port=8083
    rest.port=8083

    # Security configuration
    security.protocol=SSL
    ssl.truststore.location=/tmp/kafka/cluster.truststore.p12
    ssl.truststore.password=password
    ssl.keystore.location=/tmp/kafka/cluster.keystore.p12
    ssl.keystore.password=password
    ssl.key.password=password

  # Custom monitoring configuration
  monitoring.properties: |
    # MirrorMaker 2 monitoring
    mirrormaker.lag.reporter.class=org.apache.kafka.connect.mirror.MirrorLagReporter
    mirrormaker.lag.reporter.interval.seconds=30
    mirrormaker.lag.reporter.topic=replica-status

    # Custom metrics
    metric.reporters=org.apache.kafka.connect.mirror.MirrorMetricsReporter
    mirror.metrics.reporter.interval.seconds=60
    mirror.metrics.reporter.topic=mirror-metrics

  # Replication policies
  replication-policies.json: |
    {
      "policies": {
        "default": {
          "class": "org.apache.kafka.connect.mirror.IdentityReplicationPolicy",
          "description": "Replicate topics with identical names"
        },
        "regional": {
          "class": "org.apache.kafka.connect.mirror.DefaultReplicationPolicy",
          "separator": ".",
          "description": "Add region prefix to topic names"
        }
      }
    }
---
# Service for MirrorMaker REST API
apiVersion: v1
kind: Service
metadata:
  name: acgs2-mirrormaker2-service
  namespace: kafka
  labels:
    app: acgs2-mirrormaker2
    acgs2/component: messaging
spec:
  type: ClusterIP
  ports:
  - name: rest-api
    port: 8083
    targetPort: 8083
    protocol: TCP
  selector:
    strimzi.io/cluster: mirrormaker2-cluster
    strimzi.io/kind: KafkaMirrorMaker2
---
# Network Policy for MirrorMaker
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mirrormaker-network-policy
  namespace: kafka
  labels:
    app: acgs2-mirrormaker2
    acgs2/component: messaging
spec:
  podSelector:
    matchLabels:
      strimzi.io/cluster: mirrormaker2-cluster
      strimzi.io/kind: KafkaMirrorMaker2
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow REST API access from monitoring
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 8083
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
  # Allow traffic to Kafka clusters
  - to:
    - podSelector:
        matchLabels:
          strimzi.io/kind: Kafka
    ports:
    - protocol: TCP
      port: 9093
  # Allow traffic to Zookeeper (if needed)
  - to:
    - podSelector:
        matchLabels:
          strimzi.io/kind: Kafka
          strimzi.io/name: "*zookeeper*"
    ports:
    - protocol: TCP
      port: 2181
---
# Prometheus monitoring for MirrorMaker
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: acgs2-mirrormaker2-monitor
  namespace: kafka
  labels:
    app: acgs2-mirrormaker2
    acgs2/component: messaging
spec:
  selector:
    matchLabels:
      strimzi.io/cluster: mirrormaker2-cluster
      strimzi.io/kind: KafkaMirrorMaker2
  endpoints:
  - port: rest-api
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - kafka
