"""Initial migration

Revision ID: 01aa37809ce7
Revises:
Create Date: 2026-01-04 23:45:04.251883

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01aa37809ce7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approval_chains",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("priority", sa.String(), nullable=False),
        sa.Column("max_escalation_level", sa.Integer(), nullable=True),
        sa.Column("emergency_override_role", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "approval_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("chain_id", sa.UUID(), nullable=False),
        sa.Column("decision_id", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("requested_by", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("priority", sa.String(), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("current_step_index", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chain_id"],
            ["approval_chains.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_approval_requests_decision_id"), "approval_requests", ["decision_id"], unique=False
    )
    op.create_index(
        op.f("ix_approval_requests_tenant_id"), "approval_requests", ["tenant_id"], unique=False
    )
    op.create_table(
        "approval_steps",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("chain_id", sa.UUID(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("timeout_minutes", sa.Integer(), nullable=False),
        sa.Column("required_approvals", sa.Integer(), nullable=True),
        sa.Column("can_escalate", sa.Boolean(), nullable=True),
        sa.Column("escalation_role", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chain_id"],
            ["approval_chains.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "approval_audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("actor_id", sa.String(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["approval_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "approval_decisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column("step_id", sa.UUID(), nullable=False),
        sa.Column("approver_id", sa.String(), nullable=False),
        sa.Column("decision", sa.String(), nullable=False),
        sa.Column("rationale", sa.String(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["approval_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["approval_steps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("approval_decisions")
    op.drop_table("approval_audit_logs")
    op.drop_table("approval_steps")
    op.drop_index(op.f("ix_approval_requests_tenant_id"), table_name="approval_requests")
    op.drop_index(op.f("ix_approval_requests_decision_id"), table_name="approval_requests")
    op.drop_table("approval_requests")
    op.drop_table("approval_chains")
    # ### end Alembic commands ###
