#!/bin/bash

# Auto-Build Environment Setup for Data Import Feature
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START REDIS (Required for job tracking)
# ============================================

echo ""
echo "Starting Redis..."
if ! docker ps | grep -q redis; then
    docker run -d -p 6379:6379 --name acgs2-redis redis:alpine
    echo -e "${GREEN}Redis started${NC}"
else
    echo -e "${YELLOW}Redis already running${NC}"
fi

wait_for_service 6379 "Redis"

# ============================================
# START BACKEND (integration-service)
# ============================================

echo ""
echo "Starting integration-service..."
cd integration-service

# Check if virtual environment exists
if [ ! -d "venv" ]; then
    echo "Creating virtual environment..."
    python3 -m venv venv
fi

# Activate venv and install dependencies
source venv/bin/activate
pip install -q -r requirements.txt

# Start service in background
uvicorn src.main:app --reload --port 8000 &
BACKEND_PID=$!

cd ..

wait_for_service 8000 "integration-service"

# ============================================
# START FRONTEND (analytics-dashboard)
# ============================================

echo ""
echo "Starting analytics-dashboard..."
cd analytics-dashboard

# Install dependencies if needed
if [ ! -d "node_modules" ]; then
    echo "Installing npm dependencies..."
    npm install
fi

# Start dev server in background
npm run dev &
FRONTEND_PID=$!

cd ..

wait_for_service 3000 "analytics-dashboard"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Redis:                redis://localhost:6379"
echo "  integration-service:  http://localhost:8000"
echo "  API Docs:             http://localhost:8000/docs"
echo "  analytics-dashboard:  http://localhost:3000"
echo "  Import Page:          http://localhost:3000/import"
echo ""
echo "Process IDs:"
echo "  Backend PID:  $BACKEND_PID"
echo "  Frontend PID: $FRONTEND_PID"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID $FRONTEND_PID"
echo "  docker stop acgs2-redis"
echo ""
echo "Logs:"
echo "  Backend:  tail -f integration-service/logs/service.log"
echo "  Frontend: Check the terminal where npm run dev is running"
echo ""
echo -e "${GREEN}Ready to start building!${NC}"
echo "========================================"
