"""
ACGS-2 Data Package
Constitutional Hash: cdd01ef066bc6cf2

Contains reference baseline data for drift detection and data generation utilities.

Files:
- reference/training_baseline.csv: Pre-generated baseline dataset (CSV format)
- reference/training_baseline.parquet: Baseline dataset (parquet format, generated by setup_baseline.py)
- generate_baseline.py: Utility to generate baseline datasets programmatically
- setup_baseline.py: Converts CSV to parquet and validates the baseline

Usage:
    # Generate new baseline
    python -m enhanced_agent_bus.data.generate_baseline --samples 500

    # Convert CSV to parquet
    python -m enhanced_agent_bus.data.setup_baseline
"""

from pathlib import Path

# Package paths
DATA_DIR = Path(__file__).parent
REFERENCE_DIR = DATA_DIR / "reference"
BASELINE_CSV_PATH = REFERENCE_DIR / "training_baseline.csv"
BASELINE_PARQUET_PATH = REFERENCE_DIR / "training_baseline.parquet"


def get_baseline_path() -> Path:
    """
    Get the path to the baseline dataset.

    Returns parquet path if it exists, otherwise CSV path.

    Returns:
        Path to the baseline dataset
    """
    if BASELINE_PARQUET_PATH.exists():
        return BASELINE_PARQUET_PATH
    elif BASELINE_CSV_PATH.exists():
        return BASELINE_CSV_PATH
    else:
        raise FileNotFoundError(
            f"Baseline dataset not found. Expected at {BASELINE_PARQUET_PATH} or {BASELINE_CSV_PATH}"
        )


__all__ = [
    "DATA_DIR",
    "REFERENCE_DIR",
    "BASELINE_CSV_PATH",
    "BASELINE_PARQUET_PATH",
    "get_baseline_path",
]
