openapi: 3.0.3
info:
  title: Enhanced Agent Bus API
  description: |
    High-performance multi-agent communication infrastructure with constitutional compliance validation.

    All messages are validated against constitutional hash `cdd01ef066bc6cf2` before processing.

    ## Key Features
    - Constitutional compliance validation
    - Multi-tenant isolation
    - MACI role separation (Trias Politica)
    - Fire-and-forget metering
    - Antifragility components (health aggregation, recovery orchestration, chaos testing)

    ## Performance Metrics
    - P99 Latency: 0.278ms (target <5ms)
    - Throughput: 6,310 RPS (target >100 RPS)
    - Cache Hit Rate: 95% (target >85%)
  version: 2.4.0
  contact:
    name: ACGS-2 Team
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8080
    description: Local development
  - url: https://api.acgs2.io
    description: Production

tags:
  - name: Lifecycle
    description: Bus lifecycle operations (start/stop)
  - name: Agents
    description: Agent registration and discovery
  - name: Messages
    description: Message sending and receiving
  - name: Metrics
    description: Bus metrics and health
  - name: MACI
    description: MACI role enforcement operations

paths:
  /agents:
    get:
      tags:
        - Agents
      summary: List all registered agents
      operationId: listAgents
      parameters:
        - name: type
          in: query
          description: Filter by agent type
          schema:
            type: string
          example: governance
        - name: capability
          in: query
          description: Filter by capability
          schema:
            type: string
          example: policy_validation
        - name: tenant_id
          in: query
          description: Filter by tenant ID
          schema:
            type: string
            pattern: '^tenant-[a-zA-Z0-9-]+$'
          example: tenant-123
      responses:
        '200':
          description: List of registered agents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AgentInfo'
        '401':
          $ref: '#/components/responses/Unauthorized'
      security:
        - BearerAuth: []

    post:
      tags:
        - Agents
      summary: Register a new agent
      operationId: registerAgent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentRegistration'
      responses:
        '201':
          description: Agent registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentInfo'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          description: Agent already registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - BearerAuth: []

  /agents/{agent_id}:
    get:
      tags:
        - Agents
      summary: Get agent information
      operationId: getAgent
      parameters:
        - $ref: '#/components/parameters/AgentId'
      responses:
        '200':
          description: Agent information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentInfo'
        '404':
          $ref: '#/components/responses/NotFound'
      security:
        - BearerAuth: []

    delete:
      tags:
        - Agents
      summary: Unregister an agent
      operationId: unregisterAgent
      parameters:
        - $ref: '#/components/parameters/AgentId'
      responses:
        '204':
          description: Agent unregistered successfully
        '404':
          $ref: '#/components/responses/NotFound'
      security:
        - BearerAuth: []

  /messages:
    post:
      tags:
        - Messages
      summary: Send a message through the bus
      description: |
        Send a message with constitutional validation.

        The message must include a valid constitutional hash matching `cdd01ef066bc6cf2`.

        Messages are validated through:
        1. Constitutional hash verification
        2. Tenant isolation check
        3. MACI role enforcement (if enabled)
        4. Policy validation (if dynamic policy enabled)
      operationId: sendMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentMessage'
      responses:
        '200':
          description: Message processed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResult'
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResult'
        '403':
          description: Constitutional hash mismatch or MACI violation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResult'
      security:
        - BearerAuth: []

  /messages/broadcast:
    post:
      tags:
        - Messages
      summary: Broadcast message to all agents
      description: |
        Broadcast a message to all registered agents within the same tenant.

        The sender is automatically excluded from recipients.
      operationId: broadcastMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentMessage'
      responses:
        '200':
          description: Broadcast results per agent
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/ValidationResult'
      security:
        - BearerAuth: []

  /messages/receive:
    get:
      tags:
        - Messages
      summary: Receive next message from queue
      operationId: receiveMessage
      parameters:
        - name: timeout
          in: query
          description: Timeout in seconds to wait for message
          schema:
            type: number
            default: 5.0
            minimum: 0.1
            maximum: 60.0
      responses:
        '200':
          description: Message received
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentMessage'
        '204':
          description: No message available within timeout
      security:
        - BearerAuth: []

  /metrics:
    get:
      tags:
        - Metrics
      summary: Get bus metrics
      operationId: getMetrics
      responses:
        '200':
          description: Current bus metrics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusMetrics'
      security:
        - BearerAuth: []

  /health:
    get:
      tags:
        - Metrics
      summary: Get health status
      operationId: getHealth
      responses:
        '200':
          description: Health snapshot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthSnapshot'

  /lifecycle/start:
    post:
      tags:
        - Lifecycle
      summary: Start the agent bus
      operationId: startBus
      responses:
        '200':
          description: Bus started successfully
        '409':
          description: Bus already running
      security:
        - InternalApiKey: []

  /lifecycle/stop:
    post:
      tags:
        - Lifecycle
      summary: Stop the agent bus
      operationId: stopBus
      responses:
        '200':
          description: Bus stopped successfully
        '409':
          description: Bus not running
      security:
        - InternalApiKey: []

  /maci/validate:
    post:
      tags:
        - MACI
      summary: Validate MACI action
      description: |
        Validate if an agent is allowed to perform a specific MACI action.

        ## Role Permissions
        | Role | Allowed Actions |
        |------|-----------------|
        | EXECUTIVE | PROPOSE, SYNTHESIZE, QUERY |
        | LEGISLATIVE | EXTRACT_RULES, SYNTHESIZE, QUERY |
        | JUDICIAL | VALIDATE, AUDIT, QUERY |
        | OBSERVER | QUERY |
      operationId: validateMACIAction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MACIValidationRequest'
      responses:
        '200':
          description: Validation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MACIValidationResult'
      security:
        - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT Bearer token
    InternalApiKey:
      type: apiKey
      in: header
      name: X-Internal-API-Key
      description: Internal service API key

  parameters:
    AgentId:
      name: agent_id
      in: path
      required: true
      description: Unique agent identifier
      schema:
        type: string
        pattern: '^[a-zA-Z0-9-]+$'
      example: agent-001

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    AgentRegistration:
      type: object
      required:
        - agent_id
      properties:
        agent_id:
          type: string
          description: Unique agent identifier
          pattern: '^[a-zA-Z0-9-]+$'
          example: agent-001
        agent_type:
          type: string
          description: Agent type classification
          example: governance
        capabilities:
          type: array
          items:
            type: string
          description: Agent capabilities
          example: ["policy_validation", "audit"]
        metadata:
          type: object
          additionalProperties: true
          description: Additional metadata
        tenant_id:
          type: string
          description: Multi-tenant isolation ID
          pattern: '^tenant-[a-zA-Z0-9-]+$'
          example: tenant-123
        maci_role:
          $ref: '#/components/schemas/MACIRole'

    AgentInfo:
      allOf:
        - $ref: '#/components/schemas/AgentRegistration'
        - type: object
          properties:
            registered_at:
              type: string
              format: date-time
              description: Registration timestamp
            constitutional_hash:
              type: string
              description: Constitutional hash at registration
              example: cdd01ef066bc6cf2

    AgentMessage:
      type: object
      required:
        - from_agent
        - message_type
        - content
        - constitutional_hash
      properties:
        message_id:
          type: string
          format: uuid
          description: Unique message identifier
        conversation_id:
          type: string
          format: uuid
          description: Conversation tracking ID
        from_agent:
          type: string
          description: Sender agent ID
          example: agent-001
        to_agent:
          type: string
          description: Target agent ID (optional for broadcast)
          example: agent-002
        message_type:
          $ref: '#/components/schemas/MessageType'
        content:
          type: object
          additionalProperties: true
          description: Message payload
        priority:
          $ref: '#/components/schemas/Priority'
        tenant_id:
          type: string
          description: Tenant isolation ID
          pattern: '^tenant-[a-zA-Z0-9-]+$'
        constitutional_hash:
          type: string
          description: Constitutional compliance hash
          example: cdd01ef066bc6cf2
        headers:
          type: object
          additionalProperties:
            type: string
          description: Additional headers
        expires_at:
          type: string
          format: date-time
          description: Message expiration time
        impact_score:
          type: number
          format: float
          minimum: 0
          maximum: 1
          description: AI-assessed impact score

    MessageType:
      type: string
      enum:
        - command
        - query
        - response
        - event
        - notification
        - heartbeat
        - governance_request
        - governance_response
        - constitutional_validation
        - task_request
        - task_response
      description: Type of message

    Priority:
      type: string
      enum:
        - low
        - medium
        - high
        - critical
      default: medium
      description: Message priority level

    ValidationResult:
      type: object
      properties:
        is_valid:
          type: boolean
          description: Whether validation passed
        errors:
          type: array
          items:
            type: string
          description: Validation errors
        warnings:
          type: array
          items:
            type: string
          description: Validation warnings
        decision:
          type: string
          enum: [ALLOW, DENY, ESCALATE]
          description: Validation decision
        metadata:
          type: object
          additionalProperties: true
          description: Additional validation metadata
        constitutional_hash:
          type: string
          description: Constitutional hash used for validation

    BusMetrics:
      type: object
      properties:
        messages_sent:
          type: integer
          description: Total messages sent
        messages_received:
          type: integer
          description: Total messages received
        messages_failed:
          type: integer
          description: Total failed messages
        messages_processed:
          type: integer
          description: Total processed messages
        registered_agents:
          type: integer
          description: Currently registered agents
        constitutional_compliance:
          type: number
          format: float
          description: Compliance percentage (0-100)
        p99_latency_ms:
          type: number
          format: float
          description: P99 latency in milliseconds
        throughput_rps:
          type: number
          format: float
          description: Current throughput (requests/second)
        uptime_seconds:
          type: integer
          description: Bus uptime in seconds
        circuit_breaker_states:
          type: object
          additionalProperties:
            type: string
            enum: [CLOSED, OPEN, HALF_OPEN]
          description: Circuit breaker states by name

    HealthSnapshot:
      type: object
      properties:
        score:
          type: number
          format: float
          minimum: 0
          maximum: 1
          description: Overall health score
        status:
          type: string
          enum: [healthy, degraded, critical, unknown]
          description: System health status
        timestamp:
          type: string
          format: date-time
          description: Snapshot timestamp
        components:
          type: object
          additionalProperties:
            type: object
            properties:
              score:
                type: number
                format: float
              status:
                type: string
          description: Component health details

    MACIRole:
      type: string
      enum:
        - executive
        - legislative
        - judicial
        - observer
      description: MACI role for Trias Politica enforcement

    MACIAction:
      type: string
      enum:
        - propose
        - extract_rules
        - validate
        - audit
        - synthesize
        - query
      description: MACI action type

    MACIValidationRequest:
      type: object
      required:
        - agent_id
        - action
      properties:
        agent_id:
          type: string
          description: Agent requesting the action
        action:
          $ref: '#/components/schemas/MACIAction'
        context:
          type: object
          additionalProperties: true
          description: Additional context for validation

    MACIValidationResult:
      type: object
      properties:
        allowed:
          type: boolean
          description: Whether the action is allowed
        reason:
          type: string
          description: Reason for decision
        agent_role:
          $ref: '#/components/schemas/MACIRole'
        constitutional_hash:
          type: string
          description: Constitutional hash for audit

    Error:
      type: object
      properties:
        detail:
          type: string
          description: Error description
        error_code:
          type: string
          description: Error code
        timestamp:
          type: string
          format: date-time
          description: Error timestamp
